files:
  - source: /**/**/res/values/
    translation: /**/res/values-%android_code%/%file_name%.xml
    languages_mapping:
      android_code:
        eu: en-rEU
        es-ES: en-rES
<<<<<<< HEAD
        ar: ar-rAE
=======
>>>>>>> c9de880f2fa299afcf5d3618253bd33d536dbaaa
        ca: en-rCA
        en: en-rUS
        hr: en-rHR
        cs: en-rCS
        nl: en-rNL
        fr: en-rFR
        de: en-rDE
        el: en-rGR
        he: en-rHE
        hu: en-rHU
        it: en-rIT
        pl: en-rPL
        pt-PT: en-rPT
        pt-BR: en-rBR
        ru: en-rRU
        sk: en-rSK
        sl: en-rSI
        tr: en-rTR
        vi: vi-rVN
        fa: fa-rAF
        ar: ar-rSA
    translate_content: 0
    translate_attributes: 0
    content_segmentation: 0
