files:
  - source: /**/**/res/values/
    translation: /**/res/values-%android_code%/%file_name%.xml
    languages_mapping:
      android_code:
        eu: en-rEU
        es-ES: en-rES
        ca: en-rCA
        en: en-rUS
        hr: en-rHR
        cs: en-rCS
        nl: en-rNL
        fr: en-rFR
        de: en-rDE
        el: en-rGR
        he: en-rHE
        hu: en-rHU
        it: en-rIT
        pl: en-rPL
        pt-PT: en-rPT
        pt-BR: en-rBR
        ru: en-rRU
        sk: en-rSK
        sl: en-rSI
        tr: en-rTR
        vi: en-rVN
        fa: en-rAF
        ar: en-rSA
        th: en-rTH
        bg: en-rBG
        gl: en-rGL
        uk: en-rUK
        se: en-rSE
    translate_content: 0
    translate_attributes: 0
    content_segmentation: 0
